### ISSUE TITLE
In build phase when I use  -r @cypress/instrument-cra build it gives EPIPE error

### ISSUE THREAD

**Issue by pushkar-tal** [cypress-io/instrument-cra#168]
at internal/child_process.js:810:39
 at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
 code: 'EPIPE',
syscall: 'write'
 }
npm ERR! code ELIFECYCLE

**Comment by pushkar-tal** [comment]
Closing this
