### ISSUE TITLE
In build phase when I use -r @cypress/instrument-cra build it gives EPIPE error

### ISSUE THREAD

**Issue by DevendraShrivastava1989** [cypress-io/instrument-cra#169]
at internal/child_process.js:810:39
at processTicksAndRejections (internal/process/task_queues.js:79:11) {
errno: 'EPIPE',
code: 'EPIPE',
syscall: 'write'
}
npm ERR! code ELIFECYCLE

**Comment by DevendraShrivastava1989** [comment]
It is resolved by some configuration changes.
