### ISSUE TITLE
Does not work with yarn workspaces

### ISSUE THREAD

**Issue by jsphstls** [cypress-io/instrument-cra#25]
```
yarn run v1.15.2
$ react-scripts -r @cypress/instrument-cra start
internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module '/monorepo/packages/my-react-app/node_modules/react-scripts/config/webpack.config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (monorepo/node_modules/@cypress/instrument-cra/index.js:17:24)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
error Command failed with exit code 1.
```

This is looking for `node_modules/react-scripts/config/webpack.config.js`, but this file would actually exist higher up where `yarn workspaces` uses a single `node_modules` for all workspaces that use the same version of `react-scripts` as a dependency.

**Comment by YacheLee** [comment]
I am facing the same problem

**Comment by YacheLee** [comment]
I've solved this issue. You need to upgrade your react-scripts to 3.3.0 versions.
```
"dependencies": {
    "react-scripts": "3.3.0"
}
```

**Comment by jsphstls** [comment]
Thanks @YacheLee , I can confirm that this error no longer appears with your solution.

**Comment by jhpedemonte** [comment]
Doesn't work for me, even with react-scripts v3.3.0.

**Comment by 16patsle** [comment]
Had the same problem, fixed it by symlinking `node_modules/react-scripts/config/webpack.config.js` to where it actually is. I also had to mess around with the last line in the index.js file because require.cache didn't work properly.

Edit: Ended up patching in #63

**Comment by oailloud** [comment]
Hello! I confirm it works, it points to the react-scripts at the root of the workspace.

But in my case, this is a problem: I had to "nohoist" the react-scripts because of versions issues, so I have a yarn workspace but the react-scripts are not in the root, they are in the current directory (from which I launch `react-scripts -r @cypress/instrument-cra start`).

Any chance it might become configurable? Or maybe the script could try first the current node_modules and then look for the workspace root as a fallback? What do you think? Thanks.
